name: "Package Version Check"
description: "Get the latest version of the published package"
inputs:
  accessToken:
    description: github access token
    required: true
  debug:
    description: show debug logs
    required: false
  name:
    description: Name of the package
    required: true
  repo:
    description: Name of the repository
    required: true
  owner:
    description: owner of repo
    required: true
outputs:
  version: # id of output
    description: "The version of the package"
runs:
  using: "node12"
  main: "dist/index.js"
